#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# root level inclusions
#------------------------------------------------------------------------------
#rootLevelMappings()
npm-build.sh=
npm-build.xml=

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#determineCICDPlatformFiles()

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#determineDeploymentPlan()

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
README.md=.bankingonangular
server.js=.bankingonangular
package.json=.bankingonangular
tsconfig.json=.bankingonangular

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
mongoDb.js=.$appName.config

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
index.html=.$appName.src
styles.css=.$appName.src
polyfills.ts=.$appName.src

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
app_routing.module.ts=.$appName.src.app
app.component.css=.$appName.src.app
app.component.html=.$appName.src.app
app.component.spec.ts=.$appName.src.app
app.component.ts=.$appName.src.app
app.module.ts=.$appName.src.app
routerConfig.ts=.$appName.src.app

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
compiled.min.js=$appName.src.assets.js

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
compiled.min.css=$appName.src.assets.css

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
environment*.ts=.$appName.src.environments

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
index.component.*=.$appName.src.app.components.$className.index
create.component.*=.$appName.src.app.components.$className.create
edit.component.*=.$appName.src.app.components.$className.edit


#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
__classes__.js=.$appName.src.app.models
EnumTypes.js=.$appName.src.app.models

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
__classes__.service.spec.ts=.$appName.src.app.services
__classes__.service.ts=.$appName.src.app.services

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
exclusions=bootstrap*,compiled.min.*,mappings.properties,options.json,blueprint.json
